{ tests_not_transparent.inc }

{ Contains all tests which first keep Transparent at FALSE. }

{ included by BitmapTransparentTests.pas }

{------------------------------------------------------------------------------}
{                  Tests working with Transparent = false                      }
{------------------------------------------------------------------------------}

// Draw 24-bpp test image with Transparent = false
procedure TDrawTransparentBitmapTest_24Bit_NotTransparent.NotTransparent;
begin
  inherited;
end;

// Assign 24-bpp test bitmap to TImage.Picture with Transparent = false
procedure TAssignTransparentBitmapTest_24Bit_NotTransparent.NotTransparent;
begin
  inherited;
end;

// Draw 32-bpp test image with Transparent = false
procedure TDrawTransparentBitmapTest_32Bit_NotTransparent.NotTransparent;
begin
  inherited;
end;

// Assign 32-bpp test bitmap to TImage.Picture with Transparent = false
procedure TAssignTransparentBitmapTest_32Bit_NotTransparent.NotTransparent;
begin
  inherited;
end;


